spring: 
 profiles: 
  active: 
   -dev
---
spring: 
 profiles: dev #开发环境
 application: 
  name: microservices-config-atguigu-dev
---
spring: 
 profiles: test #测试环境
 application: 
  name: microservices-config-atguigu-test
